# Generated by Django 4.0.2 on 2022-02-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя работника')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
        ),
    ]
