# Generated by Django 4.0.2 on 2022-02-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_visits', to='users.user', verbose_name='Работник'),
        ),
    ]
