# Generated by Django 4.0.2 on 2022-02-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopvisit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopvisit',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_visits', to='shops.shop', verbose_name='Торговая точка'),
        ),
    ]
